Library_Management_System.web/Controllers/IssueBookTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMgtSystemDB;

namespace Library_Management_System.web.Controllers
{
    public class IssueBookTablesController : Controller
    {
        private LMSContext db = new LMSContext();

        // GET: IssueBookTables
        public ActionResult Issuebooks()
        {
            var issueBookTables = db.IssueBookTables.Include(i => i.BookTable).Include(i => i.EmployeeTable).Include(i => i.UserTable).Where(x=>x.Status == true);
            return View(issueBookTables.ToList());
        }

        public ActionResult Reservebooks()
        {
            var issueBookTables = db.IssueBookTables.Include(i => i.BookTable).Include(i => i.EmployeeTable).Include(i => i.UserTable).Where(x => x.ReserveCopies == true);
            return View(issueBookTables.ToList());
        }

        public ActionResult ReturnPending()
        {
            var issueBookTables = db.IssueBookTables.Where(x=>x.Status == true || x.ReserveCopies == true).ToList();
            List<IssueBookTable> list = new List<IssueBookTable>();
            foreach (var item in issueBookTables)
            {
                var returndate = item.ReturnDate;
                int Noofdays = (returndate - DateTime.Now.Date).Days;
                if(Noofdays <= 3)
                {
                    list.Add(new IssueBookTable
                    {
                        IssueBookID = item.IssueBookID,
                        BookID = item.BookID,
                        BookTable = item.BookTable,
                        EmployeeID = item.EmployeeID,
                        EmployeeTable = item.EmployeeTable,
                        UserID = item.UserID,
                        UserTable =item.UserTable,
                        NoOfCopies = item.NoOfCopies,
                        IssueDate = item.IssueDate,
                        ReturnDate = item.ReturnDate,
                        Status = item.Status, 
                        ReserveCopies =item.ReserveCopies,
                        Description = item.Description,
                    });
                    
                }
                
            }

            return View(list.ToList());
        }

        // GET: IssueBookTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IssueBookTable issueBookTable = db.IssueBookTables.Find(id);
            if (issueBookTable == null)
            {
                return HttpNotFound();
            }
            return View(issueBookTable);
        }

        // GET: IssueBookTables/Create
        public ActionResult Create()
        {
            ViewBag.BookID = new SelectList(db.BookTables, "BookID", "BookTitle");
            ViewBag.EmployeeID = new SelectList(db.EmployeeTables, "EmployeeID", "EmployeeName");
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "UserName");
            return View();
        }

        // POST: IssueBookTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IssueBookTable issueBookTable)
        {
            if (ModelState.IsValid)
            {
                var issuebook = db.IssueBookTables.Where(x => x.ReturnDate > DateTime.Now && x.BookID == issueBookTable.BookID).ToList();
                int issuebookcount = 0;
                foreach (var item in issuebook)
                {
                    issuebookcount = issuebookcount + item.NoOfCopies;
                }

                var findbook = db.BookTables.Where(x => x.BookID == issueBookTable.BookID).FirstOrDefault();
                decimal bookstocks = findbook.TotalCopies;
                if(issuebookcount + issueBookTable.NoOfCopies > bookstocks)
                { 
                    if(issuebookcount >= bookstocks)
                    {
                    ViewBag.message = "Stock is Empty...";
                    return RedirectToAction("Issuebooks");
                    }
                       ViewBag.message = "Stock is less than..."+ issueBookTable.NoOfCopies ;
                       return RedirectToAction("Create");
                }

                db.IssueBookTables.Add(issueBookTable);
                db.SaveChanges();
                return RedirectToAction("Issuebooks");
            }

            ViewBag.BookID = new SelectList(db.BookTables, "BookID", "BookTitle", issueBookTable.BookID);
            ViewBag.EmployeeID = new SelectList(db.EmployeeTables, "EmployeeID", "EmployeeName", issueBookTable.EmployeeID);
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "UserName", issueBookTable.UserID);
            return View(issueBookTable);
        }

        // GET: IssueBookTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IssueBookTable issueBookTable = db.IssueBookTables.Find(id);
            if (issueBookTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.BookID = new SelectList(db.BookTables, "BookID", "BookTitle", issueBookTable.BookID);
            ViewBag.EmployeeID = new SelectList(db.EmployeeTables, "EmployeeID", "EmployeeName", issueBookTable.EmployeeID);
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "UserName", issueBookTable.UserID);
            return View(issueBookTable);
        }

        // POST: IssueBookTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IssueBookID,NoOfCopies,IssueDate,ReturnDate,Status,ReserveCopies,Description,UserID,BookID,EmployeeID")] IssueBookTable issueBookTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(issueBookTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BookID = new SelectList(db.BookTables, "BookID", "BookTitle", issueBookTable.BookID);
            ViewBag.EmployeeID = new SelectList(db.EmployeeTables, "EmployeeID", "EmployeeName", issueBookTable.EmployeeID);
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "UserName", issueBookTable.UserID);
            return View(issueBookTable);
        }

        // GET: IssueBookTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IssueBookTable issueBookTable = db.IssueBookTables.Find(id);
            if (issueBookTable == null)
            {
                return HttpNotFound();
            }
            return View(issueBookTable);
        }

        // POST: IssueBookTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IssueBookTable issueBookTable = db.IssueBookTables.Find(id);
            db.IssueBookTables.Remove(issueBookTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult returnbook(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }
            int userid = Convert.ToInt32(Convert.ToString(Session["userid"]));

            var book = db.IssueBookTables.Find(id);
            int fine = 0;
            var returndate = book.ReturnDate;
            int noofdays = (DateTime.Now.Date - returndate).Days;
            if(book.Status == true && book.ReserveCopies == false)
            {
                if(noofdays > 0)
                {
                    fine = noofdays * 20;
                }
                var returnbook = new BookReturn
                {
                    IssueDate = book.IssueDate,
                    ReturnDate = book.ReturnDate,
                    CurrentDate = DateTime.Now,
                    BookID = book.BookID,
                    EmployeeID = book.EmployeeID,
                    UserID = book.UserID,

                };
                db.BookReturns.Add(returnbook);
                db.SaveChanges();
            }

            book.Status = false;
            book.ReserveCopies = false;
            db.Entry(book).State = EntityState.Modified;
            db.SaveChanges();

            if(fine > 0)
            {
                var addfine = new BookFineTable
                {
                    BookID = book.BookID,
                    EmployeeID = book.EmployeeID,
                    FineAmount = fine,
                    FineDate = DateTime.Now,
                    NoOfDays = noofdays,
                    ReceiveAmount = 0,
                    UserID = userid,
                };
                db.BookFineTables.Add(addfine);
                db.SaveChanges();
            }


            return RedirectToAction("Issuebooks");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Library_Management_System.web/Controllers/ReserveBookController.cs
using LibraryMgtSystemDB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Management_System.web.Controllers
{
    public class ReserveBookController : Controller
    {
        LMSContext db = new LMSContext();
        // GET: ReserveBook
        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var reservelist = db.BookTables.ToList();
            return View(reservelist);
        }

        public ActionResult Reservebook(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var userid = Convert.ToInt32(Session["userid"]);
            var employeeid = Convert.ToInt32(Session["employeeid"]);
            var book = db.BookTables.Find(id);
            var issuebook = db.IssueBookTables.Where(x => x.ReturnDate > DateTime.Now && x.BookID == id).ToList();

            int issuebookcount = 0;
            foreach (var item in issuebook)
            {
                issuebookcount = issuebookcount + item.NoOfCopies;
            }

            //var findbook = db.BookTables.Where(x => x.BookID == issueBookTable.BookID).FirstOrDefault();

            var issuebooktable = new IssueBookTable()
            {
                BookID = book.BookID,
                NoOfCopies = 1,
                IssueDate = DateTime.Now,
                ReturnDate = DateTime.Now.AddDays(2),
                Description = "Reserve",
                Status = false,
                ReserveCopies = true,
                UserID = userid,
                EmployeeID = employeeid,
            };

            decimal bookstocks = book.TotalCopies;

            if (issuebookcount >= bookstocks)
            {
                ViewBag.message = "Stock is Empty...";
                return RedirectToAction("index");
            }

            db.IssueBookTables.Add(issuebooktable);
            db.SaveChanges();
            ViewBag.message = "Successfully Reserved...";
            return RedirectToAction("index");
        }

        public ActionResult ApproveBook(int? id)
        {
            var findbook = db.IssueBookTables.Find(id);
            findbook.ReserveCopies = false;
            findbook.Status = true;
            db.Entry(findbook).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Issuebooks","Issuebooktables");
        }
    }
}

Library_Management_System.web/Views/IssueBookTables/Create.cshtml
@model LibraryMgtSystemDB.IssueBookTable

@{
    ViewBag.Title = "Create";
    ViewBag.heading = "All Issue Book >";

}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Issue Book</h6>
            <h4>@ViewBag.message</h4>
        </div>
        <div class="card-body">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.EmployeeID, "Employee", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BookID, "Book", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BookID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BookID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NoOfCopies, "No of Copies", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoOfCopies, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoOfCopies, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IssueDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IssueDate, "Issue Date", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IssueDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReturnDate, "Return Date", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReturnDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReturnDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserID, "User", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Status)
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.ReserveCopies, "Reserve", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.ReserveCopies)
                        @Html.ValidationMessageFor(model => model.ReserveCopies, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
        </div>
        }

Library_Management_System.web/Views/IssueBookTables/Delete.cshtml
@model LibraryMgtSystemDB.IssueBookTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>IssueBookTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookTable.BookTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookTable.BookTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeTable.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeTable.EmployeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoOfCopies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoOfCopies)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IssueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReserveCopies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReserveCopies)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Library_Management_System.web/Views/IssueBookTables/Details.cshtml
@model LibraryMgtSystemDB.IssueBookTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>IssueBookTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookTable.BookTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookTable.BookTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeTable.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeTable.EmployeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoOfCopies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoOfCopies)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IssueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReserveCopies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReserveCopies)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IssueBookID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Library_Management_System.web/Views/IssueBookTables/Edit.cshtml
@model LibraryMgtSystemDB.IssueBookTable

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>IssueBookTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IssueBookID)

        <div class="form-group">
            @Html.LabelFor(model => model.NoOfCopies, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoOfCopies, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfCopies, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IssueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IssueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IssueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReserveCopies, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ReserveCopies)
                    @Html.ValidationMessageFor(model => model.ReserveCopies, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookID, "BookID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BookID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BookID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeID, "EmployeeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Library_Management_System.web/Views/IssueBookTables/Reservebooks.cshtml
@model IEnumerable<LibraryMgtSystemDB.IssueBookTable>

@{
    ViewBag.Title = "Reservebooks";
    ViewBag.heading = "All Issue Book >";

}

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Reserve Books</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Book Title
                        </th>
                        <th>
                            Employee Name
                        </th>
                        <th>
                            User Name
                        </th>
                        <th>
                            No of Copiew
                        </th>
                        <th>
                            Issue Date
                        </th>
                        <th>
                            Return Date
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Status)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.BookTable.BookTitle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EmployeeTable.EmployeeName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserTable.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NoOfCopies)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IssueDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ReturnDate)
                            </td>
                            <td>
                                <p class="btn btn-outline-info" style="font:bold">Reserve</p>  
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td class="btn-group">
                                @Html.ActionLink("Return Book", "returnbook", new { id = item.IssueBookID }, new { @class = "btn btn-primary" })
                                @Html.ActionLink("Approve", "ApproveBook", "ReserveBook", new { id = item.IssueBookID }, new { @class = "btn btn-success" })
                                @Html.ActionLink("Delete", "Delete", new { id = item.IssueBookID }, new { @class = "btn btn-danger" })

                            </td>
                        </tr>
                    }

            </table>
        </div>
    </div>
</div>