Library_Management_System.web/Controllers/PurchaseTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMgtSystemDB;
using Library_Management_System.web.Models;

namespace Library_Management_System.web.Controllers
{
    public class PurchaseTablesController : Controller
    {
        decimal totalamount = 0;
        private LMSContext db = new LMSContext();

        // GET: PurchaseTables
        public ActionResult NewPurchase()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }
            decimal totalamount = 0;
            var purlist = db.PurTemDetailsTables.ToList();
            foreach(var item in purlist)
            {
                totalamount += (item.Qty * item.UnitPrice);
            }
            ViewBag.TotalAmount = totalamount;
            return View(purlist);
        }

        [HttpPost]
        public ActionResult Additem(int BID, int Qty, int price)
        {
           
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var find = db.PurTemDetailsTables.Where(p=>p.BookID == BID).FirstOrDefault();
            if (find == null)
            {
               if( BID > 0 && Qty > 0 && price > 0)
                {
                    var newtiem = new PurTemDetailsTable()
                    {
                        BookID = BID,
                        Qty = Qty,
                        UnitPrice = price,
                    };

                    db.PurTemDetailsTables.Add(newtiem);
                    db.SaveChanges();
                    ViewBag.message = "Purchase Item Added Successfully.....";
                }
            }
            else
            {
                ViewBag.warning = "Already Exist Please Check.....";
               
                var purtemlist = db.PurTemDetailsTables.ToList();
                foreach (var item in purtemlist)
                {
                    totalamount += (item.Qty * item.UnitPrice);
                }
                ViewBag.TotalAmount = totalamount;
                return View("NewPurchase", purtemlist);
            }
            var purlist = db.PurTemDetailsTables.ToList();
            foreach (var item in purlist)
            {
                totalamount += (item.Qty * item.UnitPrice);
            }
            ViewBag.TotalAmount = totalamount;
            return View("NewPurchase", purlist);
        }

        public ActionResult GetBooks()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }
            List<BookMV> list = new List<BookMV>();
            var booklist = db.BookTables.ToList();
            foreach (var item in booklist)
            {
                list.Add(new BookMV { BookName = item.BookName, BookID = item.BookID });
            }
            return Json(new { data = list }, JsonRequestBehavior.AllowGet);
        }


        //POST: PurchaseTables/Delete/5
        [ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }
            PurTemDetailsTable purtemdetails = db.PurTemDetailsTables.Find(id);
            db.PurTemDetailsTables.Remove(purtemdetails);
            db.SaveChanges();
            ViewBag.delete = "Deleted Successfully.....";
            var purlist = db.PurTemDetailsTables.ToList();
            foreach (var item in purlist)
            {
                totalamount += (item.Qty * item.UnitPrice);
            }
            ViewBag.TotalAmount = totalamount;
            return View("NewPurchase", purlist);
        }



      
        public ActionResult CancelPurchase()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }

            var list = db.PurTemDetailsTables.ToList();
            var cancelstatus = false;
            foreach(var item in list)
            {
                db.Entry(item).State = EntityState.Deleted;
               int noofrecord = db.SaveChanges();
                   if(cancelstatus == false)
                {
                    if(noofrecord > 0)
                    {
                        cancelstatus = true;
                    }
                }
            }
            if (cancelstatus == true)
            {
                ViewBag.cancel = "Purchase's Cancel Successfully.......";
                var purlist = db.PurTemDetailsTables.ToList();
                return RedirectToAction("NewPurchase", purlist);
            }
            return RedirectToAction("NewPurchase");
        }

        public ActionResult SelectSupplier()
        {
            var purchasetemlist = db.PurTemDetailsTables.ToList();
            
            if (purchasetemlist.Count == 0)
            {
                ViewBag.purtemmessage = "Purchase Cart Is Empty....";
                var purlist = db.PurTemDetailsTables.ToList();
                return RedirectToAction("NewPurchase", purlist);
            }
            var supplierlist = db.SupplierTables.ToList();
            return View(supplierlist);
        }

     
        public ActionResult PurchaseConfirm(FormCollection collection)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }
            int userid = Convert.ToInt32(Convert.ToString(Session["userid"]));
            int supplierid = 0;
            string[] key = collection.AllKeys;
            foreach(var name in key)
            {
                if (name.Contains("name"))
                {
                string nameid = name;
                string[] valueid = nameid.Split(' ');
                supplierid = Convert.ToInt32(valueid[1]);
                }
            }

            var purtemdetails = db.PurTemDetailsTables.ToList();
            decimal totalamount = 0;
            foreach (var item in purtemdetails)
            {
                totalamount = totalamount + (item.Qty * item.UnitPrice);
            }
            if(totalamount == 0)
            {
                ViewBag.message = "Purchase Cart Empty....";
                var purlist = db.PurTemDetailsTables.ToList();
                return RedirectToAction("NewPurchase", purlist);
            }

            var purchasetable = new PurchaseTable()
            {
                SupplierID = supplierid,
                UserID = userid,
                PurchaseDate = DateTime.Now,
                PurchaseAmount = totalamount,
            };
            db.PurchaseTables.Add(purchasetable);
            db.SaveChanges();

            foreach(var item in purtemdetails)
            {
                var purchasedetails = new PurchaseDetailsTable()
                {
                    PurchaseID = purchasetable.PurchaseID,
                    BookID = item.BookID,
                    Qty = item.Qty,
                    UnitPrice = item.UnitPrice,
                };
                db.PurchaseDetailsTables.Add(purchasedetails);
                db.SaveChanges();

                var updatestock = db.BookTables.Find(item.BookID);
                if(updatestock != null)
                {
                    updatestock.TotalCopies = updatestock.TotalCopies + item.Qty;
                    updatestock.Price = item.UnitPrice;

                    db.Entry(updatestock).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }

            var list = db.PurTemDetailsTables.ToList();
            var cancelstatus = false;
            foreach (var item in list)
            {
                db.Entry(item).State = EntityState.Deleted;
                int noofrecord = db.SaveChanges();
                if (cancelstatus == false)
                {
                    if (noofrecord > 0)
                    {
                        cancelstatus = true;
                    }
                }
            }
            if (cancelstatus == true)
            {
                ViewBag.purchaseconfirm = "Purchase's Cancel Successfully.......";
                //var purlist = db.PurTemDetailsTables.ToList();
                //return RedirectToAction("NewPurchase", purlist);
            }



            return RedirectToAction("AllPurchase");
        }

        public ActionResult AllPurchase()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var list = db.PurchaseTables.ToList();
            return View(list);
        }

        public ActionResult PurchaseDetail()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var list = db.PurchaseDetailsTables.ToList();
            return View(list);
        }

        //// GET: PurchaseTables/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
        //    {
        //        return RedirectToAction("Login", "Home");
        //    }
        //    if (string.IsNullOrEmpty(Convert.ToString(Session["userid"])))
        //    {
        //        return RedirectToAction("Login", "Home");
        //    }
        //    if (id == null)
        //    {

Library_Management_System.web/Views/PurchaseTables/AllPurchase.cshtml
@model IEnumerable<LibraryMgtSystemDB.PurchaseTable>

@{
    ViewBag.Title = "AllPurchase";
    ViewBag.heading = "All Purchase >";

}
@Html.ActionLink("New Purchase", "NewPurchase", null, new { @class = "btn btn-primary" })
<hr />
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">All Purchase</h6>
        <h6>@ViewBag.delete</h6>

    </div>
    <div class="card-body">
        <div class="table-hover">
            <table class="table table-bordered" id="dataTable" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Supplier Name
                        </th>
                        <th>
                            User Name
                        </th>
                        <th>
                            Purchase Date
                        </th>
                        <th>
                            Purchase Amount
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.SupplierTable.SupplierName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserTable.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PurchaseDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PurchaseAmount)
                            </td>
                            <td >
                                @Html.ActionLink("Edit", "Edit", new { id = item.PurchaseID }, new { @class = "btn btn-primary" })
                                @Html.ActionLink("Details", "PurchaseDetail", new { id = item.PurchaseID }, new { @class = "btn btn-info" })
                                @Html.ActionLink("Delete", "Delete", new { id = item.PurchaseID }, new { @class = "btn btn-danger" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Library_Management_System.web/Views/PurchaseTables/Create.cshtml
@model LibraryMgtSystemDB.PurchaseTable

@{
    ViewBag.Title = "Create";
    ViewBag.heading = "All Purchase >";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit Purchase</h6>
        </div>
        <div class="card-body">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PurchaseAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PurchaseAmount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PurchaseAmount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SupplierID, "SupplierID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SupplierID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
        </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

Library_Management_System.web/Views/PurchaseTables/Delete.cshtml
@model LibraryMgtSystemDB.PurchaseTable

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PurchaseTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SupplierTable.SupplierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SupplierTable.SupplierName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseAmount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Library_Management_System.web/Views/PurchaseTables/Details.cshtml
@model LibraryMgtSystemDB.PurchaseTable

@{
    ViewBag.Title = "Details";
    ViewBag.heading = "All Purchase";
}

<div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Details Purchase</h6>
        </div>
        <div class="card-body">
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.SupplierTable.SupplierName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SupplierTable.SupplierName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UserTable.UserName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserTable.UserName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PurchaseDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PurchaseDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PurchaseAmount)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PurchaseAmount)
                </dd>

            </dl>
        </div>
    </div>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.PurchaseID }) |
            @Html.ActionLink("Back to List", "Index")
        </p>

Library_Management_System.web/Views/PurchaseTables/Edit.cshtml
@model LibraryMgtSystemDB.PurchaseTable

@{
    ViewBag.Title = "Edit";
    ViewBag.heading = "All Purchase >";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit Purchase</h6>
        </div>
        <div class="card-body">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.PurchaseID)

            <div class="form-group">
                @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PurchaseAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PurchaseAmount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PurchaseAmount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SupplierID, "SupplierID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SupplierID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
        </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

Library_Management_System.web/Views/PurchaseTables/NewPurchase.cshtml
@model IEnumerable<LibraryMgtSystemDB.PurTemDetailsTable>

@{
    ViewBag.Title = "New Purchase";
    ViewBag.heading = "All Purchase >";

}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
@using (Html.BeginForm("Additem", "PurchaseTables", FormMethod.Post, null))
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">New Purchase</h6>
            <h6>@ViewBag.message</h6>
            <h6>@ViewBag.warning</h6>
            <h6>@ViewBag.cancel</h6>
        </div>
        <div class="card-body">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @*@Html.LabelFor(model => model., htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
                    </div>*@
                <label class="control-label col-md-2">Select Book</label>
                <div class="col-md-6">
                    <select class="form-control" id="BID" name="BID" required></select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Quantity</label>
                <div class="col-md-6">
                    <input type="number" class="form-control" id="Qty" name="Qty" placeholder="Enter Quantity" required>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Unit Price</label>
                <div class="col-md-6">
                    <input type="number" class="form-control" id="price" name="price" placeholder="Enter Price" required>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add Item" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}



<hr />
@if (Model != null)
{
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Purchase Cart</h6>
            <h6>@ViewBag.delete</h6>

        </div>
        <div class="card-body">
            <div class="table-hover">
                <table class="table table-bordered" id="dataTable" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                Book
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th>
                                Unit Price
                            </th>
                            <th>
                                Item Cost
                            </th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.BookTable.BookName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Qty)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UnitPrice)
                                </td>
                                <td>
                                    @(item.Qty * item.UnitPrice)
                                </td>
                                <td>
                                    @Html.ActionLink("Delete", "Delete", new { id = item.PurTemDetailsID }, new { @class = "btn btn-danger" })
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td></td>
                            <td></td>
                            <td style="background-color: black; color:white">Total Bill</td>
                            <td style="background-color: black; color:white">
                                @*(string.Format("{0:0.000}", Math.Truncate(ViewBag.TotalAmount * 10) / 10))PKR;*@
                                @ViewBag.TotalAmount PKR
                            </td>

                            <td></td>
                        </tr>
                    </tfoot>
                </table>
                <div class="col-md-4 col-md-offset-8" style="float:right">
                    @Html.ActionLink("Next", "SelectSupplier", null, new { @class = "btn btn-success" })
                    @Html.ActionLink("Cancel", "CancelPurchase", null, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </div>
}

<script>
    $(document).ready(function () {

        $.ajax({
            url: '@Url.Action("GetBooks", "PurchaseTables")',
            type: 'Get',
            data: '{}',

            success: function (response) {
                for (var i = 0; i < response.data.length; i++){
                    $('#BID').append("<option value =" + response.data[i].BookID + ">" + response.data[i].BookName + "</option>");
                }
            },
            error: function () { }
        });
    });
</script>

Library_Management_System.web/Views/PurchaseTables/SelectSupplier.cshtml
@model IEnumerable<LibraryMgtSystemDB.SupplierTable>

@{
    ViewBag.Title = "SelectSupplier";
    ViewBag.heading = "All Purchase >";

}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

@using (Html.BeginForm("PurchaseConfirm", "PurchaseTables", FormMethod.Post))
{

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Finilize Purchase</h6>
            <input type="submit" value="Finilize Purchase" class="btn btn-success" style="float:right" />
        </div>
        <div class="card-body">
            <div class="table-hover">
                <table class="table table-bordered" id="dataTable" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                User Name
                            </th>
                            <th>
                                Supplier Name
                            </th>
                            <th>
                                Contact No
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>Select Supplier</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserTable.UserName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SupplierName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ContactNo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    <input type="checkbox" class="chk" name="name @item.SupplierID" />
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        $('.chk').change(function (event) {
            $('.chk').prop('checked', false);
            $(this).prop('checked', true);
        });
    });
</script>